modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="factoriores"
version="${file.jarVersion}"
displayName="FactoriOres"
authors="Seraphaestus"
description='''
Factoriores is a mod that adds ores and miners inspired by the game Factorio
'''

[[dependencies.factoriores]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.factoriores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.factoriores]]
    modId="create"
    mandatory=false
    versionRange="[mc1.16.5_v0.3.1,)"
    ordering="AFTER"
    side="BOTH"